// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:93c2df6b-f4cd-47d1-bac1-0da5e43c33e9",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_vMZeC4B6w",
    "aws_user_pools_web_client_id": "2h83lern406392ipj5h2rdf743",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://rd2ywxpmcjgqbgpfblgksph5xu.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
